server:
  addr: 0.0.0.0:8848

datasource:
  dsn: nju:${NJU_PASSWORD}@tcp(124.223.97.89:3306)/sentisamoyed?characterEncoding=utf8&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true